export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const EMAIL_SEND_FAIL = "EMAIL_SEND_FAIL";
export const EMAIL_SEND_SUCCESS = "EMAIL_SEND_SUCESS";

export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCESS";

export const VERIFY_FAIL = "VERIFY_FAIL"
export const VERIFY_SUCCESS = "VERIFY_SUCCESS"

export const REGISTER_FAIL = "REGISTER_FAIL"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"